# Generated by Django 4.1.7 on 2023-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(upload_to='upload/feeds/images', verbose_name='Bild'),
        ),
    ]
