# Generated by Django 4.1.7 on 2023-04-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(upload_to='static/images/uploads/feed', verbose_name='Bild'),
        ),
    ]
