# Generated by Django 4.1.7 on 2023-04-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_feed_likes_count_feedlikes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedlikes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='feed',
            name='likes_count',
        ),
    ]
