# Generated by Django 4.1.7 on 2023-04-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_feedlikes_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pp',
            field=models.ImageField(null=True, upload_to='static/images/uploads/profile', verbose_name='Profilbild'),
        ),
    ]
