# Generated by Django 4.1.7 on 2023-04-26 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_feed_published_date_alter_feed_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ['-published_date', '-id']},
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_fulname', models.BooleanField(default=True, verbose_name='Vollständige Name anzeigen')),
                ('safemode', models.BooleanField(default=False, verbose_name='Safe Mode')),
                ('graphic_interface', models.CharField(choices=[('Light Mode', 'Light Mode'), ('Dark Mode', 'Dark Mode')], default='Light Mode', max_length=50, verbose_name='Benutzeroberfläche')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
