# Generated by Django 4.1.7 on 2023-05-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_settings_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.settings'),
        ),
    ]
