# Generated by Django 4.1.7 on 2023-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_settings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='majestic_id',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Majestic ID'),
            preserve_default=False,
        ),
    ]
