# Generated by Django 4.1.7 on 2023-05-01 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_user_majestic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='majestic_id',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000000)], verbose_name='Majestic ID'),
        ),
    ]
