# Generated by Django 4.1.7 on 2023-05-01 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_delete_stone_delete_wood'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuser',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='followuser',
            unique_together={('follower', 'follow')},
        ),
    ]
